### ISSUE TITLE
kdpatch.sys is flagged as malware

### ISSUE THREAD

**Issue by snowkoan** [4d61726b/VirtualKD-Redux#11]
**Describe the bug**
Not exactly a bug, but something of note -- some versions of kdpatch.sys are being flagged as malware. For example: 

https://www.virustotal.com/gui/file/c1c0bda0bd4d36288696e6f5a8b2e4d22c1862b00f74c4550e5beb8476ed8c6a/detection

**To Reproduce**
1. Grab the 2019.6 release
2. Upload the target64\kdpatch.sys file to https://www.virustotal.com/gui/home/upload

**Expected behavior**
File should not be flagged as malware. 
1. If this is malware, please let us know so we can stop using it :-)
2. If it's not malware, maybe signing it would help? At least some of the detections appear to be heuristic-based.

**Screenshots**

![image](https://user-images.githubusercontent.com/5479011/80505248-13b99e00-8942-11ea-90d9-da2e84e170db.png)

**Configuration (please complete the following information):**
 - VirtualKD-Redux 2019.6
 - VMware or VirtualBox version: n/a
 - OS running on the host: Windows 10 1903
 - OS running in the guest VM: Windows 7 x64

**Comment by 4d61726b** [comment]
Do you use vminstall.exe in the guest vm? If so, kdpatch.sys is not in the equation. I think most (if not all) users do not use kdpatch.sys and I'm not even sure that it still works. It was written by Sysprogs at some point and would do the kdcom patching on the fly. This is different from vminstall which will modify the boot configuration to using kdbazis as the kdcom provider. That is much cleaner and safer.

I've been tempted to remove it since I think nobody ever uses it but I left it in there for educational value. I am more tempted to remove it now if its creating a nuisance for people running anti-virus software on their computer.

**Comment by snowkoan** [comment]
Ah, thanks for explaining.

Yes, I use vminstall.exe in the guest VM.

And yes, I would agree that removing kdpatch.sys is the way to go. You can't even run an unsigned driver on Windows these days (AFAIK) but all these AV vendors flag it all the same. Perhaps you could leave the source for educational value.

**Comment by 4d61726b** [comment]
Removed kdpatch in VirtualKD-Redux 2020.2.
