### ISSUE TITLE
The box is empty

### ISSUE THREAD

**Issue by XxBrokenComputerxX** [4d61726b/VirtualKD-Redux#15]
**Describe the bug**
When I run a VM and it run debugger it (and hit break) it doesn't show anything. I'm pretty sure I installed it correctly. However I'm a noob. Relatively new to programming and completely new to driver programming so it might be my fault. If so I'm sorry.

**To Reproduce**
Run VM, look at your application: empty box, no matter what you press

**Expected behavior**
It should say something like in the tutorial

**Screenshots**
https://imgur.com/a/e7NVdeQ

**Configuration (please complete the following information):**
 - VirtualKD-Redux version [e.g. 2020.2]
 - VMware or VirtualBox version [VMware Workstation Pro 15.5.5 build- 16285975]
 - OS running on the host [Windows 8.1 PRO (last release pretty sure) 64-bit]
 - OS running in the guest VM [Windows 10 PRO 1909 64-bit]

**Comment by 4d61726b** [comment]
Thanks for the description and the screenshot. That is very strange. I was concerned that it could be related to 15.5.5 but I just tried it on my copy and it worked fine. I tried it with the kernel mode VMM which is what you should be using if you're on Windows 8.1 Pro since that doesn't support VBS.

I'm unable to reproduce this, so let's try the following:

1. Ensure that in the guest you ran vminstall.exe.
2. Completely shut down the guest, and restart the host machine.
3. When the host machine boots back up, start VMware Workstation.
4. Start vmmon.
5. Start the guest machine. By the time you get to the windows boot menu in the guest, vmmon should report that everything is good and it was able to patch. You should be seeing debug messages in the text box and there should be a green light.
6. Select in the guest's boot menu the option to disable driver signature enforcement.

If the debugger path has been set up correctly, windbg should pop up after you selected to disable driver signature enforcement and continued booting.

Let me know how that goes and we'll work from there.

**Comment by 4d61726b** [comment]
I'm assuming this isn't an issue anymore. If it still is, reopen the ticket and we'll figure it out from there.

**Comment by XxBrokenComputerxX** [comment]
Yea I just resolved it myself. Sorry for late reply I was busy and only just looked into it!
