### ISSUE TITLE
BSOD vmware16+win10x64 

### ISSUE THREAD

**Issue by kahotv** [4d61726b/VirtualKD-Redux#21]
**Describe the bug**
disable driver signature -> BSOD

Host:
...

**To Reproduce**
1. Copy 'target64' to Target Machine d:\target64
2. Run d:\target64\vminstall.exe
3. Click Install,and nextnextnext..
4. reboot
5. select VKD Item,F8, select disable driver signature
6. BSOD

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/41276366/94833722-0b5e1580-0442-11eb-8493-ced1a7a59b30.png)
![image](https://user-images.githubusercontent.com/41276366/94833999-66900800-0442-11eb-8e71-d106914a71a2.png)

**Configuration (please complete the following information):**
 - 2020.3
 - VMware Workstation 16.0.0 build-16894299
 - Windows 10 2004 64-bit
 - Windows 10 2004 64-bit

more:
![image](https://user-images.githubusercontent.com/41276366/94834750-5dec0180-0443-11eb-981f-7724917f11bc.png)

VKD-Redux + disable signature -> BSOD
windows 10 + disable signature ->no BSOD

**Comment by 4d61726b** [comment]
I'm able to reproduce this issue if vmmon64 is **not** already running. Were you running vmmon64 before booting into Windows? This is a workaround for now.

The problem seems to stem from returning a failure back to Windows during the boot process in the case where the host side isn't ready for communication yet (i.e. kdclient has not been loaded in the vmx process). I am still looking into it.

**Comment by 4d61726b** [comment]
I believe this issue is now fixed in VirtualKD-Redux 2020.4.
