### ISSUE TITLE
Useless. Doesn't work whatsoever

### ISSUE THREAD

**Issue by Terrydaktal** [4d61726b/VirtualKD-Redux#29]
Doesn't work on windows 7 with virtualbox 5.1. VMs don't show up. VirtualboxIntegration.exe only crashes.

![image](https://user-images.githubusercontent.com/24293492/114815122-7b643580-9dad-11eb-8a8b-8d5720c16ced.png)

**Comment by 4d61726b** [comment]
I'm not surprised that the COM object has changed. You're using a version that hasn't been supported by Oracle since early 2018. The latest version of VirtualKD-Redux works with the latest version of VirtualBox (6.1) and I would suggest updating to that if you can.

If you are unwilling to upgrade, you can try dropping in the VirtualBoxIntegration.exe file from the original VirtualKD (Version 3.0) into your VirtualKD-Redux folder. You might have some luck with that, but no guarantees. I strongly suggest updating VirtualBox instead.
