### ISSUE TITLE
WinDBG Preview from windows store launch error

### ISSUE THREAD

**Issue by buridan1999** [4d61726b/VirtualKD-Redux#36]
**Describe the bug**
When I tried to launch WinDBG Preview version from VirtualKD, it's failed. On Windows 10, the last version of windbg can be started only as app.

**To Reproduce**
1. Install WinDBG Preview from Windows Store
2. Try to start debug with VirtualKD with WinDBG Preview type, don't change path to it!

**Expected behavior**
Start of WinDBG

**Screenshots**
![image](https://user-images.githubusercontent.com/25010424/133248529-fabed5ca-1248-4fa4-bec9-d886a4d4c5f7.png)

**Configuration (please complete the following information):**
 - VirtualKD-Redux version [e.g. 2019.4]:

**Additional context**
Fix in pull-request: (https://github.com/4d61726b/VirtualKD-Redux/pull/35)

**Comment by 4d61726b** [comment]
I appreciate the bug report and the PR. Unfortunately, your code in the PR fixes the symptom of the bug and not the bug itself.

From what I can tell in your PR, the issue you had was that the sideloaded WinDbg Preview path was bad and you were getting ERROR_ACCESS_DENIED. It then seems like you later installed the version from the Microsoft Store. Because you had previously set the sideloaded path, vmmon would never try to use the installed version since the configuration superseded that.

The changes I made in 8141f11707069b5eedbc7cbe595441c8a7bd40a2 should address this. If you click the "Sideloaded WinDbg Preview Path" button now, it will detect that you have the installed version available and ask if you want to use that instead.

Additional logic was also added to that commit to attempt to prevent similar situations occurring in the future. I also got away from using ShellExecute in the event WindowsApps is not in the user's PATH.

If you have a chance, I would appreciate if you can verify that the changes I made fix your particular problem. I will eventually make a new release in the next week or so which will have this fix.
