### ISSUE TITLE
Win11 update (April 25, 2022—KB5012643 (OS Build 22000.652) - Preview) breaks VirtualKD-Redux

### ISSUE THREAD

**Issue by rodwiddowson** [4d61726b/VirtualKD-Redux#42]
I haven't fully characterized this yet but it appears that deploying this update (its marked as preliminary or some such) breaks VirtualKD.

I did a full update of Win11 (10.0.22000.593) and it was OK then I applied [KB5012643](https://support.microsoft.com/en-gb/topic/april-25-2022-kb5012643-os-build-22000-652-preview-43a75ee7-d857-4943-a2b9-f961538bd2b0)

Ver now reports (10.0.22000.652) and VirtualKD no longer works.  Further Trying to reinstall gives the popup
```
Cannot create KDBAZIS/DLL: Access is Denied
```
I have the VM snapshotted if you need me to prod further

**Configuration**
 - VirtualKD-Redux version 2021.3
 - VMware or VirtualBox version VMware 16.2.3 build-19376536
 - OS running on the host Win 10 10.0.19043.1645
 - OS running in the guest Win 11 10.0.22000.652

**Comment by rodwiddowson** [comment]
Further details:
* The version I started with was 593, but after the first set of updates (VirtualKD still OK still working) it was `Microsoft Windows [Version 10.0.22000.613]`
* If I revert the KB then ver goes back to reporting 613, but 
** VirtualKD still doesn't work
** installation still doesn't work

**Comment by rodwiddowson** [comment]
It appears that this update 
* Changes the owner of `WINDOWS\SYSTEM32\KDCOMM.DLL` to be `TrustedInstaller`
* Adds a restrictive ACL so that Administrators (at least) only have read and execute access.

Forcing ownership back to `Administrators` and then  granting that group full permission allows `VmInstall.exe` to install, after which VirtualKD-Redux starts working again.  This is a pretty heft hammer but it is effective (and my machines are only used for debugging so I am happy to leave them like that).

Thanks

**Comment by 4d61726b** [comment]
Thanks for reporting this. In newer versions of Windows, kdcom.dll has always been owned and locked down to TrustedInstaller. What you were probably seeing was VirtualKD-Redux's kdcom.dll which **not** is locked down to TrustedInstaller. Installing the KB5012643 msu overwrote that file and changed its permissions. VirtualKD-Redux's vminstall attempts to move kdcom.dll to kdcom_old.dll and because it failed (kdcom_old.dll existed and was owned by TrustedInstaller), it went down a code path that was undesirable. I fixed this issue in 66c263fdd6ed93f2125bbf979d108c5b4ffaab82 / 2022.0 by ensuring that we continue to preserve the versions of kdcom.dll that we overwrite. This fix also has a nice side effect of not having to worry about permissions since we never try to overwrite the older copies. This should address your issue, but if it doesn't let me know.

**Comment by rodwiddowson** [comment]
Confirmed that `2022.0` installs cleanly and works. 

Many thanks for your speedy response

**Comment by snowkoan** [comment]
Just had this happen this morning - thanks for characterizing it so quickly @rodwiddowson . Hope you're doing well!
