### ISSUE TITLE
TraceAssist is not working

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#52]
I try filling its dialog box out, then shutting down and relaunching the VM. No log file is being generated in the directory that I set.

**Comment by 4d61726b** [comment]
Thanks for reporting this issue! I briefly looked at the logic for TraceAssist and see some areas that can use improvement. If I have some time this weekend I'll see if I can put together some fixes that will address your issue.

**Comment by 4d61726b** [comment]
This issue has been fixed in 2023.0. There were two problems:

1. If the process in which `kdclient.dll` was loaded in was a run as different user than `vmmon64.exe`, then the TraceAssist configuration would never get properly loaded. This can happen because `vmmon64.exe` is elevated and `vmware-vmx.exe` is not.

2. The `kdclient.dll` module incorrectly accessed the TraceAssist configuration which would lead to it getting erased.

Thanks again for reporting this.
