### ISSUE TITLE
WinDbg is busy for 20+ seconds when getting a backtrace

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#53]
Can VirtualKD-Redux be modified to fix that?

**Comment by 4d61726b** [comment]
Backtraces (i.e. `k` command) should be instantaneous. What's the exact command you are issuing?

**Comment by Zero3K** [comment]
!analyze -v

**Comment by 4d61726b** [comment]
That command does significantly more than just backtracing.

The reason it's so slow is likely because of symbol loading in WinDbg which is unrelated to functionality that VirtualKD-Redux provides.

Try issuing `!sym noisy` before performing `!analyze -v`. This might give a hint as to where the bottleneck is, assuming it's related to symbols.

**Comment by 4d61726b** [comment]
I'm going to close this issue because I believe it's related to downloading symbols and not any functionality provided by VirtualKD-Redux.

If you have reason to believe it's related to VirtualKD-Redux, you can reply to this issue and we can discuss further.
