### ISSUE TITLE
vmware guest os will be red point after update to win11

### ISSUE THREAD

**Issue by spobit** [4d61726b/VirtualKD-Redux#59]
**Describe the bug**
I was updated os to win11, then the vmware guset os will be red point when starts it.

**To Reproduce**
- open win10 guest
- red point in virtualkd list
- move to virtualkd card
- f8
- disabled driver signature
- break at start screen

**Screenshots**
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/25954976/1db4e6e5-222f-48ce-80a3-c917b39a80ce)

![image](https://github.com/4d61726b/VirtualKD-Redux/assets/25954976/71e2def6-da17-4b7c-a03f-1bc2adfad072)

**Configuration (please complete the following information):**
 - VirtualKD-Redux version [e.g. 2019.4]: 2023.0
 - VMware or VirtualBox version [e.g. VMware Workstation 15.5.0 build-14665864]: VMware Workstation 17.5.0 build-22583795
 - OS running on the host [e.g. Windows 10 1903 64-bit]:
        OS Name:                   Microsoft Windows 11 Pro
        OS Version:                10.0.22631 N/A Build 22631
 - OS running in the guest VM [e.g. Windows 7 SP1 32-bit]:
        OS Name:                   Microsoft Windows 10 Pro
        OS Version:                10.0.19045 N/A Build 19045

**Additional context**

**Comment by 4d61726b** [comment]
Thanks for filling out the template. I have a similar configuration as yours and it works for me, so something on your host might be preventing `vmmon64.exe` from loading `kdclient.dll` into the vmx process.

Can you:

1. Close everything on your host, including VMware Workstation and `vmmon64.exe`
2. Start VMware Workstation
3. Start the VM, but just press F8, don't disable driver signature enforcement. Stay at the menu.
4. Start `vmxpatch64.exe`
5. Select the one VM to patch and apply the patch

Can you post the output / result of this? Does `vmxpatch64.exe` succeed? I am hoping that this would give us a hint as to what the issue is.

**Comment by spobit** [comment]
@4d61726b 
VirtualKD-Redux 2023.0

Listing detected VM sessions:

#       PID     Name
1       14656
------------------------------------
Which VM session to patch/unpatch? (1-1): 1
The vmware-vmx.exe has been successfully patched. You can now use the debugger.
Do you want to unpatch it back? (y/n)

**Comment by 4d61726b** [comment]
Can you exit everything and perform the steps again?

This time, once it successfully patched (as seen in your reply), **don't unpatch it (specify `n`)**. Then start `vmmon64.exe`. Is the VM "green" this time and not "red"? If it's green, can you disable driver signature enforcement in the VM and see if you can kernel debug?

**Comment by spobit** [comment]
@4d61726b 
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/25954976/70f9c823-e251-447f-85a5-a8c9bd18aa71)

**Comment by spobit** [comment]
reinstall win11, everything is ok.
