### ISSUE TITLE
Windows 11 integration isn't working

### ISSUE THREAD

**Issue by Zero3K** [4d61726b/VirtualKD-Redux#62]
I installed the dll in the target64 directory (along with the patches being checked) and set it to replace the default boot entry ans enabled it via the integration program. The VM shows with a green circle but WinDbg doesn't run (and running it via Start debugger causes it to show "waiting for reconnect").

**Comment by 4d61726b** [comment]
Works fine for me, I'm going to need more information about your setup and exact steps to reproduce.

**Comment by Zero3K** [comment]
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/6194332/f7938526-ddcb-40e6-b9d8-c3a9b9c19324)

**Comment by 4d61726b** [comment]
Is there a reason why you're still using an old version of 6 instead of upgrading to 7? Windows 11 isn't even officially supported as a guest on that version. Can you try with VirtualBox 7 instead?

**Comment by Zero3K** [comment]
I upgraded to VirtualBox 7. The issue is still occurring.

**Comment by 4d61726b** [comment]
Well, it works great for me. I'm going to need more steps on how to reproduce it beyond a screenshot.

**Comment by Zero3K** [comment]
I do not know what to tell you.

**Comment by 4d61726b** [comment]
Can you show me the "Motherboard" tab under "Settings->System" for that VM?

**Comment by Zero3K** [comment]
![image](https://github.com/4d61726b/VirtualKD-Redux/assets/6194332/28fa96ea-a094-430f-92b2-5cf63cbdd12f)

**Comment by 4d61726b** [comment]
A minute after it freezes can you pull the logs and upload them here? Make sure you wait a minute after it happens, then go to "Machine->Show Log" and upload both the VBox.log and VBoxHardening.log

**Comment by Zero3K** [comment]
It doesn't freeze.

**Comment by Zero3K** [comment]
Oh, I still had to disable driver signature enforcement even though I re-signed it with a test certificate and had test signing mode enabled.

**Comment by 4d61726b** [comment]
My bad, I looked at your other screenshot and thought the "About screen" was the "boot splash screen".

> Oh, I still had to disable driver signature enforcement even though I re-signed it with a test certificate and had test signing mode enabled.

See my comment here, it's not possible to sign that DLL in Windows 8 and above to bypass that restriction:

https://github.com/4d61726b/VirtualKD-Redux/issues/7#issuecomment-602036883

So this issue is resolved then?

**Comment by 4d61726b** [comment]
When I asked for the steps to reproduce, you only posted a screenshot. I asked again and you said:

> I do not know what to tell you.

If you had told me that you were trying to self-sign the transport DLL, then I could have easily told you that wasn't going to work and it would have saved us both time.

In the future, just follow the "Bug Report" template when you file an issue on this project and try to document the exact steps you are performing so I can try to replicate the issue you're experiencing. It would save us both time instead of going back and forth to try and get the information out of you.
