### ISSUE TITLE
Is there a way not to “disable driver signature” ?

### ISSUE THREAD

**Issue by YZJClear** [4d61726b/VirtualKD-Redux#7]
I have a certificate available
I try signature to kdbazis.dll and kdbazis.dll, but it's errors if "i not disable driver sinature"
Is there a way not to “disable driver signature” ?

**Comment by 4d61726b** [comment]
What operating system version?

**Comment by YZJClear** [comment]
Windows 7 Pro x64
and
Windows 10 Pro x64 （1903）

**Comment by 4d61726b** [comment]
>Windows 8 does not normally allow custom debug transport DLLs that are not signed by Microsoft (even a valid AuthentiCode signature is not sufficient).

https://sysprogs.com/legacy/virtualkd/win8/

That also applies to Windows 10.

If the guest is Windows 7 or below, it seems to be possible as the original VirtualKD did this. You would have to purchase a kernel mode code signing certificate and there may be caveats. I would recommend ensuring that the guest has all the latest updates installed.

I can't provide any additional help with this because I don't have a code signing certificate. I would have to refer you to:

https://web.archive.org/web/20090117132733/http://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/KMCS_Walkthrough.doc

Look at "How to Release-Sign a Kernel Module"

This should give you enough information for properly signing the DLL, assuming you purchased the correct code signing certificate. To reiterate: You cannot self sign the certificate and must purchase an SPC from the list of CAs that are trusted in the guest that you are running from.

**Comment by YZJClear** [comment]
I've learned
Thank you very much!
